### ISSUE TITLE
Site Title and Tag Line Overlay menu on mobile device

### ISSUE THREAD

**Issue by cojaxx** [godaddy/wp-activation-theme#48]
Hello,
I've noticed that if the Site Title and Tag Line are quite long, and the website is being viewed on a  mobile device, the text overlays the menu items. 

Ideally I think when the menu is clicked, it hides the Site Title and Tag Lines. 

Is this able to be changed?
![image-1](https://user-images.githubusercontent.com/37229920/37235827-1716d520-243d-11e8-8884-64261c9eba2f.jpg)

**Comment by EvanHerman** [comment]
Hi @cojaxx 

You can tweak the padding on the menu to adjust for the additional length in the site title.

You can add the following CSS snippet to the 'Additional CSS' section of the customizer. You can get there from the dashboard by going to 'Appearance > Customize > Additional CSS'. 

```css
.main-navigation.open {
   padding-top: 150px;
}
```

You can tweak the value `150px` to whatever it is that works for your site.

This should end up looking similar to:
<img src="https://cldup.com/s7TYU-zmgg.png" width="275" />

Another option is to hide the Site Title altogether when the menu is open. There is a little bit more CSS involved, but is possible.

```css
.site-title-wrapper {
   z-index: auto;
}

.menu-toggle{
   top: 10px;
   right: -10px;
}

.main-navigation.open {
   padding-top: 0;
}
```

This solution should end up looking similar to:
<img src="https://cldup.com/WsTN6dUBWj.png" width="275" />

We can explore some alternatives to work around the issue in future releases.

Let us know if either solution helps out.
